In [2]:
import tensorflow as tf

print(tf.__version__)
a = tf.random.uniform([2, 3], 0, 1)
print(a)
print(type(a))

2.0.0
tf.Tensor(
[[0.09665442 0.401932   0.02143466]
 [0.12525105 0.99111927 0.16819072]], shape=(2, 3), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [3]:
import tensorflow as tf
import numpy as np

t = tf.random.uniform([2, 3], 0, 1)
n = np.random.uniform(0, 1, [2, 3])
print("tensorflow로 생성한 텐서:\n", t, "\n")
print("numpy로 생성한 ndarray:\n", n, "\n")

# 텐서 t와 ndarray n의 덧셈
res = t + n
print("덧셈 결과:\n", res)

tensorflow로 생성한 텐서:
 tf.Tensor(
[[0.05127203 0.37253022 0.58069205]
 [0.14716041 0.2685523  0.7050023 ]], shape=(2, 3), dtype=float32) 

numpy로 생성한 ndarray:
 [[0.85095241 0.13067603 0.37077624]
 [0.12375065 0.17883037 0.98717016]] 

덧셈 결과:
 tf.Tensor(
[[0.9022244  0.50320625 0.9514683 ]
 [0.27091107 0.4473827  1.6921725 ]], shape=(2, 3), dtype=float32)


In [4]:
import tensorflow as tf

# OR 데이터 구축
x = [[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]
y = [[-1], [1], [1], [1]]

# [그림 4-3(b)]의 퍼셉트론
w = tf.Variable([[1.0], [1.0]])
b = tf.Variable(-0.5)

# 식 4.3의 퍼셉트론 동작
s = tf.add(tf.matmul(x, w), b)
o = tf.sign(s)

print(o)

tf.Tensor(
[[-1.]
 [ 1.]
 [ 1.]
 [ 1.]], shape=(4, 1), dtype=float32)


In [5]:
import tensorflow as tf

# OR 데이터 구축
x = [[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]]
y = [[-1], [1], [1], [1]]

# 가중치 초기화
w = tf.Variable(tf.random.uniform([2, 1], -0.5, 0.5))
b = tf.Variable(tf.zeros([1]))

# 옵티마이저
opt = tf.keras.optimizers.SGD(learning_rate = 0.1)

# 전방 계산(식 (4.3))
def forward():
    s = tf.add(tf.matmul(x, w), b)
    o = tf.tanh(s)
    return 

# 손실 함수 정의
def loss():
    o = forward()
    return tf.reduce_mean((y - o) ** 2)

# 500세대까지 학습(100세대마다 학습 정보 출력)
for i in range(500):
    opt.minimize(loss, var_list=[w, b])
    if (i%100 == 0):
        print("loss at epoch", i, "=", loss().numpy())

# 학습된 퍼셉트론으로 OR 데이터를 예측
o = forward()
print(0)

TypeError: unsupported operand type(s) for -: 'list' and 'NoneType'